version: '3.8'

networks:
  keystone-network:
    driver: bridge

services:
  # 1. Base de données PostgreSQL pour Employee Service
  employee-db:
    image: postgres:15-alpine
    container_name: employee-db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./employee-service/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - keystone-network

  # 2. Le Microservice Node.js Employee Service
  employee-service:
    build: ./employee-service
    container_name: employee-service
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      DB_HOST: employee-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: employee_db
    depends_on:
      - employee-db
    networks:
      - keystone-network

  # 3. Kong API Gateway (Mode DB-less / Déclaratif)
  kong:
    image: kong:3.4
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000" # Point d'entrée pour React
      - "8001:8001" # Port Admin de Kong
    networks:
      - keystone-network